### ISSUE TITLE
I added this to 

### ISSUE THREAD

**Issue by staminna** [SKLINET/strapi-plugin-video-field#5]
Trying to add a video field I can preview but not render on latest version of 
https://github.com/strapi/starters-and-templates/issues/new

in node 14.0.0 and 16.16.0

% npm run develop

> my-next-blog@1.0.3 develop
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /rontend/.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
event - build page: /category/[slug]
wait  - compiling...
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
error - components/image.js (5:61) @ Image
TypeError: Cannot read properties of null (reading 'attributes')
  3 | 
  4 | const Image = ({ image, style }) => {
> 5 |   const { url, alternativeText, width, height } = image.data.attributes
    |                                                             ^
  6 | 
  7 |   // const loader = () => {
  8 |   //   return getStrapiMedia(image)
error - components/image.js (5:61) @ Image
TypeError: Cannot read properties of null (reading 'attributes')
  3 | 
  4 | const Image = ({ image, style }) => {
> 5 |   const { url, alternativeText, width, height } = image.data.attributes
    |                                                             ^
  6 | 
  7 |   // const loader = () => {
  8 |   //   return getStrapiMedia(image)

**Comment by Sklico** [comment]
Hi @staminna, I'm a little bit confused. What exactly are you trying to do ? This is video field for external videos and you've sent here some log related to image field, which is something totally different and our field doesn't return any Strapi media field. Could you be more specific please ?

Thanks a lot
Michal

**Comment by staminna** [comment]
Hi Michael,

Thanks for quickly reply
I am trying to use video uploaded directly from local storage to the Strapi
Media Galery.
Its my first Strapi project and I can see the video playing in the Backend.
Perhaps it the template starter?
Perhaps I can use Facebook vídeos

Best
Jorge

**Comment by Sklico** [comment]
Hi @staminna,
first, we support only YT, Vimeo & FB videos. For uploaded videos, there is Strapi's built in media field. This is plugin only for the external videos, we never count with the case where you upload video to the Strapi and use it in our custom field instead of default media field. Second, the output of our custom field is different than the output of Strapi media field, so the code you've provided is for the Strapi media field, you can't process our field's output like that. The output of our custom field is part of the README.

Michal
