### ISSUE TITLE
Update for compatibility with Node 20.x

### ISSUE THREAD

**Issue by scot875** [SKLINET/strapi-plugin-video-field#9]
Hello, would love to use this plug in with the latest strapi..   I'm currently running:
Strapi version
    v4.15.4
node version
    v20.10.0

Can this project be updated to run with Node 20.x?

Thanks!

**Comment by scot875** [comment]
Hello, is there any progress on this issue or potential scheduling timing?  Thanks!

**Comment by Sklico** [comment]
Hi @scot875, it should work fine in version 1.0.6. I've tested with Strapi 4.19 and Node.js 20.4.
